[package]
name = "native-webview"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "native-webview"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = "0.12.2"
serde = "1.0.132"
serde_json = "1.0.73"
crossbeam-channel = "0.5.1"
image = "0.23.14"